name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Cache poetry venv
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run black
        if: ${{ always() }}
        run: poetry run black --check plox tests
      - name: Run flake8
        if: ${{ always() }}
        run: poetry run flake8 plox tests
      - name: Run pylint
        if: ${{ always() }}
        run: poetry run pylint plox tests
      - name: Run mypy
        if: ${{ always() }}
        run: poetry run mypy plox tests

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Cache poetry venv
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run pytest
        run: poetry run pytest --cov plox
